# run with treefmt --allow-missing-formatter

[global]
excludes = [
  # gitignore
  "**/.gitignore",
  # go.sum & go.mod
  "go.sum",
  "go.mod",
  # build artifacts
  "*.so",
  "pw-convoverb",
  # log files
  "*.log",
  # coverage files
  "coverage.*",
]

### Misc

[formatter.prettier]
command = "prettier"
options = ["-w"]
includes = [
  "*.yaml",
  "*.yml",
  "*.json",
  "*.md",
]

### Go

[formatter.gofumpt]
command = "gofumpt"
options = ["-w"]
includes = ["*.go"]

[formatter.gci]
command = "gci"
options = [
  "write",
  "--skip-generated",
  "-s",
  "standard",
  "-s",
  "default",
  "-s",
  "prefix(github.com/MeKo-Christian/algo-fft)",
  "-s",
  "blank",
]
includes = ["*.go"]
priority = 1 # run after gofumpt to ensure import ordering is final

### C

[formatter.clang-format]
command = "clang-format"
options = ["-i"]
includes = ["*.c", "*.h"]
